//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSBalanceClient.PGPersonAllocateInfoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseModel", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGPersonAllocateInfoService.WebsiteInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGPersonAllocateInfoService.PersonGoldBaseModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGPersonAllocateInfoService.PGPersonInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo))]
    public partial class BaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderbyColomnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubOrderbyColomnNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndIndex {
            get {
                return this.EndIndexField;
            }
            set {
                if ((this.EndIndexField.Equals(value) != true)) {
                    this.EndIndexField = value;
                    this.RaisePropertyChanged("EndIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderbyColomnName {
            get {
                return this.OrderbyColomnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderbyColomnNameField, value) != true)) {
                    this.OrderbyColomnNameField = value;
                    this.RaisePropertyChanged("OrderbyColomnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowNumber {
            get {
                return this.RowNumberField;
            }
            set {
                if ((this.RowNumberField.Equals(value) != true)) {
                    this.RowNumberField = value;
                    this.RaisePropertyChanged("RowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartIndex {
            get {
                return this.StartIndexField;
            }
            set {
                if ((this.StartIndexField.Equals(value) != true)) {
                    this.StartIndexField = value;
                    this.RaisePropertyChanged("StartIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubOrderbyColomnName {
            get {
                return this.SubOrderbyColomnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubOrderbyColomnNameField, value) != true)) {
                    this.SubOrderbyColomnNameField = value;
                    this.RaisePropertyChanged("SubOrderbyColomnName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebsiteInfo", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    public partial class WebsiteInfo : WSBalanceClient.PGPersonAllocateInfoService.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagerTelphoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewWebsiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteTelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Institution {
            get {
                return this.InstitutionField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitutionField, value) != true)) {
                    this.InstitutionField = value;
                    this.RaisePropertyChanged("Institution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerTelphone {
            get {
                return this.ManagerTelphoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerTelphoneField, value) != true)) {
                    this.ManagerTelphoneField = value;
                    this.RaisePropertyChanged("ManagerTelphone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewWebsiteID {
            get {
                return this.NewWebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NewWebsiteIDField, value) != true)) {
                    this.NewWebsiteIDField = value;
                    this.RaisePropertyChanged("NewWebsiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteAddress {
            get {
                return this.WebsiteAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteAddressField, value) != true)) {
                    this.WebsiteAddressField = value;
                    this.RaisePropertyChanged("WebsiteAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteID {
            get {
                return this.WebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteIDField, value) != true)) {
                    this.WebsiteIDField = value;
                    this.RaisePropertyChanged("WebsiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteManager {
            get {
                return this.WebsiteManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteManagerField, value) != true)) {
                    this.WebsiteManagerField = value;
                    this.RaisePropertyChanged("WebsiteManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteName {
            get {
                return this.WebsiteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteNameField, value) != true)) {
                    this.WebsiteNameField = value;
                    this.RaisePropertyChanged("WebsiteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteTel {
            get {
                return this.WebsiteTelField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteTelField, value) != true)) {
                    this.WebsiteTelField = value;
                    this.RaisePropertyChanged("WebsiteTel");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonGoldBaseModel", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGPersonAllocateInfoService.PGPersonInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo))]
    public partial class PersonGoldBaseModel : WSBalanceClient.PGPersonAllocateInfoService.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewWebsiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataTime {
            get {
                return this.DataTimeField;
            }
            set {
                if ((this.DataTimeField.Equals(value) != true)) {
                    this.DataTimeField = value;
                    this.RaisePropertyChanged("DataTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewWebsiteID {
            get {
                return this.NewWebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NewWebsiteIDField, value) != true)) {
                    this.NewWebsiteIDField = value;
                    this.RaisePropertyChanged("NewWebsiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteID {
            get {
                return this.WebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteIDField, value) != true)) {
                    this.WebsiteIDField = value;
                    this.RaisePropertyChanged("WebsiteID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PGPersonInfo", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    public partial class PGPersonInfo : WSBalanceClient.PGPersonAllocateInfoService.PersonGoldBaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffPositionOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSBalanceClient.PGPersonAllocateInfoService.WebsiteInfo WebsiteInfoObjField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardID {
            get {
                return this.CardIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CardIDField, value) != true)) {
                    this.CardIDField = value;
                    this.RaisePropertyChanged("CardID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffCode {
            get {
                return this.StaffCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffCodeField, value) != true)) {
                    this.StaffCodeField = value;
                    this.RaisePropertyChanged("StaffCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffName {
            get {
                return this.StaffNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffNameField, value) != true)) {
                    this.StaffNameField = value;
                    this.RaisePropertyChanged("StaffName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffPosition {
            get {
                return this.StaffPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffPositionField, value) != true)) {
                    this.StaffPositionField = value;
                    this.RaisePropertyChanged("StaffPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffPositionOrder {
            get {
                return this.StaffPositionOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffPositionOrderField, value) != true)) {
                    this.StaffPositionOrderField = value;
                    this.RaisePropertyChanged("StaffPositionOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffType {
            get {
                return this.StaffTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffTypeField, value) != true)) {
                    this.StaffTypeField = value;
                    this.RaisePropertyChanged("StaffType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSBalanceClient.PGPersonAllocateInfoService.WebsiteInfo WebsiteInfoObj {
            get {
                return this.WebsiteInfoObjField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteInfoObjField, value) != true)) {
                    this.WebsiteInfoObjField = value;
                    this.RaisePropertyChanged("WebsiteInfoObj");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PGPersonAllocateInfo", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    public partial class PGPersonAllocateInfo : WSBalanceClient.PGPersonAllocateInfoService.PersonGoldBaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CardDayGrowthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CardMonthGrowthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CardYearGrowthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CreditCardDayGrowthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CreditCardMonthGrowthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CreditCardYearGrowthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DayContributionDegreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InsuranceDayGrowthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InsuranceMonthGrowthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InsuranceYearGrowthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MonthContributionDegreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSBalanceClient.PGPersonAllocateInfoService.PGPersonInfo PGPersonInfoObjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PreRankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSBalanceClient.PGPersonAllocateInfoService.WebsiteInfo WebsiteInfoObjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal YearContributionDegreeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CardDayGrowth {
            get {
                return this.CardDayGrowthField;
            }
            set {
                if ((this.CardDayGrowthField.Equals(value) != true)) {
                    this.CardDayGrowthField = value;
                    this.RaisePropertyChanged("CardDayGrowth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CardMonthGrowth {
            get {
                return this.CardMonthGrowthField;
            }
            set {
                if ((this.CardMonthGrowthField.Equals(value) != true)) {
                    this.CardMonthGrowthField = value;
                    this.RaisePropertyChanged("CardMonthGrowth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CardYearGrowth {
            get {
                return this.CardYearGrowthField;
            }
            set {
                if ((this.CardYearGrowthField.Equals(value) != true)) {
                    this.CardYearGrowthField = value;
                    this.RaisePropertyChanged("CardYearGrowth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CreditCardDayGrowth {
            get {
                return this.CreditCardDayGrowthField;
            }
            set {
                if ((this.CreditCardDayGrowthField.Equals(value) != true)) {
                    this.CreditCardDayGrowthField = value;
                    this.RaisePropertyChanged("CreditCardDayGrowth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CreditCardMonthGrowth {
            get {
                return this.CreditCardMonthGrowthField;
            }
            set {
                if ((this.CreditCardMonthGrowthField.Equals(value) != true)) {
                    this.CreditCardMonthGrowthField = value;
                    this.RaisePropertyChanged("CreditCardMonthGrowth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CreditCardYearGrowth {
            get {
                return this.CreditCardYearGrowthField;
            }
            set {
                if ((this.CreditCardYearGrowthField.Equals(value) != true)) {
                    this.CreditCardYearGrowthField = value;
                    this.RaisePropertyChanged("CreditCardYearGrowth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DayContributionDegree {
            get {
                return this.DayContributionDegreeField;
            }
            set {
                if ((this.DayContributionDegreeField.Equals(value) != true)) {
                    this.DayContributionDegreeField = value;
                    this.RaisePropertyChanged("DayContributionDegree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InsuranceDayGrowth {
            get {
                return this.InsuranceDayGrowthField;
            }
            set {
                if ((this.InsuranceDayGrowthField.Equals(value) != true)) {
                    this.InsuranceDayGrowthField = value;
                    this.RaisePropertyChanged("InsuranceDayGrowth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InsuranceMonthGrowth {
            get {
                return this.InsuranceMonthGrowthField;
            }
            set {
                if ((this.InsuranceMonthGrowthField.Equals(value) != true)) {
                    this.InsuranceMonthGrowthField = value;
                    this.RaisePropertyChanged("InsuranceMonthGrowth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InsuranceYearGrowth {
            get {
                return this.InsuranceYearGrowthField;
            }
            set {
                if ((this.InsuranceYearGrowthField.Equals(value) != true)) {
                    this.InsuranceYearGrowthField = value;
                    this.RaisePropertyChanged("InsuranceYearGrowth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MonthContributionDegree {
            get {
                return this.MonthContributionDegreeField;
            }
            set {
                if ((this.MonthContributionDegreeField.Equals(value) != true)) {
                    this.MonthContributionDegreeField = value;
                    this.RaisePropertyChanged("MonthContributionDegree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSBalanceClient.PGPersonAllocateInfoService.PGPersonInfo PGPersonInfoObj {
            get {
                return this.PGPersonInfoObjField;
            }
            set {
                if ((object.ReferenceEquals(this.PGPersonInfoObjField, value) != true)) {
                    this.PGPersonInfoObjField = value;
                    this.RaisePropertyChanged("PGPersonInfoObj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PreRank {
            get {
                return this.PreRankField;
            }
            set {
                if ((this.PreRankField.Equals(value) != true)) {
                    this.PreRankField = value;
                    this.RaisePropertyChanged("PreRank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffCode {
            get {
                return this.StaffCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffCodeField, value) != true)) {
                    this.StaffCodeField = value;
                    this.RaisePropertyChanged("StaffCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffName {
            get {
                return this.StaffNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffNameField, value) != true)) {
                    this.StaffNameField = value;
                    this.RaisePropertyChanged("StaffName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSBalanceClient.PGPersonAllocateInfoService.WebsiteInfo WebsiteInfoObj {
            get {
                return this.WebsiteInfoObjField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteInfoObjField, value) != true)) {
                    this.WebsiteInfoObjField = value;
                    this.RaisePropertyChanged("WebsiteInfoObj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal YearContributionDegree {
            get {
                return this.YearContributionDegreeField;
            }
            set {
                if ((this.YearContributionDegreeField.Equals(value) != true)) {
                    this.YearContributionDegreeField = value;
                    this.RaisePropertyChanged("YearContributionDegree");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PGPersonAllocateInfoService.IPGPersonAllocateInfoService")]
    public interface IPGPersonAllocateInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGPersonAllocateInfoService/Add", ReplyAction="http://tempuri.org/IPGPersonAllocateInfoService/AddResponse")]
        bool Add(WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGPersonAllocateInfoService/Update", ReplyAction="http://tempuri.org/IPGPersonAllocateInfoService/UpdateResponse")]
        bool Update(WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGPersonAllocateInfoService/Delete", ReplyAction="http://tempuri.org/IPGPersonAllocateInfoService/DeleteResponse")]
        bool Delete(WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGPersonAllocateInfoService/Select", ReplyAction="http://tempuri.org/IPGPersonAllocateInfoService/SelectResponse")]
        WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo[] Select(WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGPersonAllocateInfoService/SelectCount", ReplyAction="http://tempuri.org/IPGPersonAllocateInfoService/SelectCountResponse")]
        int SelectCount(WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGPersonAllocateInfoService/CallTimeSpanProc", ReplyAction="http://tempuri.org/IPGPersonAllocateInfoService/CallTimeSpanProcResponse")]
        WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo[] CallTimeSpanProc(WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo t);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPGPersonAllocateInfoServiceChannel : WSBalanceClient.PGPersonAllocateInfoService.IPGPersonAllocateInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PGPersonAllocateInfoServiceClient : System.ServiceModel.ClientBase<WSBalanceClient.PGPersonAllocateInfoService.IPGPersonAllocateInfoService>, WSBalanceClient.PGPersonAllocateInfoService.IPGPersonAllocateInfoService {
        
        public PGPersonAllocateInfoServiceClient() {
        }
        
        public PGPersonAllocateInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PGPersonAllocateInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PGPersonAllocateInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PGPersonAllocateInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo info) {
            return base.Channel.Add(info);
        }
        
        public bool Update(WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo info) {
            return base.Channel.Update(info);
        }
        
        public bool Delete(WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo info) {
            return base.Channel.Delete(info);
        }
        
        public WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo[] Select(WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo info) {
            return base.Channel.Select(info);
        }
        
        public int SelectCount(WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo info) {
            return base.Channel.SelectCount(info);
        }
        
        public WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo[] CallTimeSpanProc(WSBalanceClient.PGPersonAllocateInfoService.PGPersonAllocateInfo t) {
            return base.Channel.CallTimeSpanProc(t);
        }
    }
}
