#pragma checksum "..\..\..\..\Views\UserControlLoading.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "13CCA0D6F2D236A60C054DA6F02D682A"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace BalanceReport.Views {
    
    
    /// <summary>
    /// UserControlLoading
    /// </summary>
    public partial class UserControlLoading : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 874 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.Animation.BeginStoryboard ProgressAnimation_BeginStoryboard;
        
        #line default
        #line hidden
        
        
        #line 886 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas LayoutRoot;
        
        #line default
        #line hidden
        
        
        #line 896 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block0;
        
        #line default
        #line hidden
        
        
        #line 910 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block1;
        
        #line default
        #line hidden
        
        
        #line 924 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block2;
        
        #line default
        #line hidden
        
        
        #line 938 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block3;
        
        #line default
        #line hidden
        
        
        #line 952 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block4;
        
        #line default
        #line hidden
        
        
        #line 966 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block5;
        
        #line default
        #line hidden
        
        
        #line 980 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block6;
        
        #line default
        #line hidden
        
        
        #line 994 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block7;
        
        #line default
        #line hidden
        
        
        #line 1008 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block8;
        
        #line default
        #line hidden
        
        
        #line 1022 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block9;
        
        #line default
        #line hidden
        
        
        #line 1036 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block10;
        
        #line default
        #line hidden
        
        
        #line 1050 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block11;
        
        #line default
        #line hidden
        
        
        #line 1064 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block12;
        
        #line default
        #line hidden
        
        
        #line 1078 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block13;
        
        #line default
        #line hidden
        
        
        #line 1092 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block14;
        
        #line default
        #line hidden
        
        
        #line 1106 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block15;
        
        #line default
        #line hidden
        
        
        #line 1120 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block16;
        
        #line default
        #line hidden
        
        
        #line 1134 "..\..\..\..\Views\UserControlLoading.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path block17;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/BalanceReport;component/views/usercontrolloading.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\UserControlLoading.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ProgressAnimation_BeginStoryboard = ((System.Windows.Media.Animation.BeginStoryboard)(target));
            return;
            case 2:
            this.LayoutRoot = ((System.Windows.Controls.Canvas)(target));
            return;
            case 3:
            this.block0 = ((System.Windows.Shapes.Path)(target));
            return;
            case 4:
            this.block1 = ((System.Windows.Shapes.Path)(target));
            return;
            case 5:
            this.block2 = ((System.Windows.Shapes.Path)(target));
            return;
            case 6:
            this.block3 = ((System.Windows.Shapes.Path)(target));
            return;
            case 7:
            this.block4 = ((System.Windows.Shapes.Path)(target));
            return;
            case 8:
            this.block5 = ((System.Windows.Shapes.Path)(target));
            return;
            case 9:
            this.block6 = ((System.Windows.Shapes.Path)(target));
            return;
            case 10:
            this.block7 = ((System.Windows.Shapes.Path)(target));
            return;
            case 11:
            this.block8 = ((System.Windows.Shapes.Path)(target));
            return;
            case 12:
            this.block9 = ((System.Windows.Shapes.Path)(target));
            return;
            case 13:
            this.block10 = ((System.Windows.Shapes.Path)(target));
            return;
            case 14:
            this.block11 = ((System.Windows.Shapes.Path)(target));
            return;
            case 15:
            this.block12 = ((System.Windows.Shapes.Path)(target));
            return;
            case 16:
            this.block13 = ((System.Windows.Shapes.Path)(target));
            return;
            case 17:
            this.block14 = ((System.Windows.Shapes.Path)(target));
            return;
            case 18:
            this.block15 = ((System.Windows.Shapes.Path)(target));
            return;
            case 19:
            this.block16 = ((System.Windows.Shapes.Path)(target));
            return;
            case 20:
            this.block17 = ((System.Windows.Shapes.Path)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

