//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSBalanceClient.AccountAndNameLinkInfoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseModel", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.AccountAndNameLinkInfoService.AccountAndNameLinkInfo))]
    public partial class BaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderbyColomnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubOrderbyColomnNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndIndex {
            get {
                return this.EndIndexField;
            }
            set {
                if ((this.EndIndexField.Equals(value) != true)) {
                    this.EndIndexField = value;
                    this.RaisePropertyChanged("EndIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderbyColomnName {
            get {
                return this.OrderbyColomnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderbyColomnNameField, value) != true)) {
                    this.OrderbyColomnNameField = value;
                    this.RaisePropertyChanged("OrderbyColomnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowNumber {
            get {
                return this.RowNumberField;
            }
            set {
                if ((this.RowNumberField.Equals(value) != true)) {
                    this.RowNumberField = value;
                    this.RaisePropertyChanged("RowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartIndex {
            get {
                return this.StartIndexField;
            }
            set {
                if ((this.StartIndexField.Equals(value) != true)) {
                    this.StartIndexField = value;
                    this.RaisePropertyChanged("StartIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubOrderbyColomnName {
            get {
                return this.SubOrderbyColomnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubOrderbyColomnNameField, value) != true)) {
                    this.SubOrderbyColomnNameField = value;
                    this.RaisePropertyChanged("SubOrderbyColomnName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountAndNameLinkInfo", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    public partial class AccountAndNameLinkInfo : WSBalanceClient.AccountAndNameLinkInfoService.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountIDField, value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountAndNameLinkInfoService.IAccountAndNameLinkInfoService")]
    public interface IAccountAndNameLinkInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountAndNameLinkInfoService/Add", ReplyAction="http://tempuri.org/IAccountAndNameLinkInfoService/AddResponse")]
        bool Add(WSBalanceClient.AccountAndNameLinkInfoService.AccountAndNameLinkInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountAndNameLinkInfoService/Update", ReplyAction="http://tempuri.org/IAccountAndNameLinkInfoService/UpdateResponse")]
        bool Update(WSBalanceClient.AccountAndNameLinkInfoService.AccountAndNameLinkInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountAndNameLinkInfoService/Delete", ReplyAction="http://tempuri.org/IAccountAndNameLinkInfoService/DeleteResponse")]
        bool Delete(WSBalanceClient.AccountAndNameLinkInfoService.AccountAndNameLinkInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountAndNameLinkInfoService/Select", ReplyAction="http://tempuri.org/IAccountAndNameLinkInfoService/SelectResponse")]
        WSBalanceClient.AccountAndNameLinkInfoService.AccountAndNameLinkInfo[] Select(WSBalanceClient.AccountAndNameLinkInfoService.AccountAndNameLinkInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountAndNameLinkInfoService/SelectCount", ReplyAction="http://tempuri.org/IAccountAndNameLinkInfoService/SelectCountResponse")]
        int SelectCount(WSBalanceClient.AccountAndNameLinkInfoService.AccountAndNameLinkInfo info);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountAndNameLinkInfoServiceChannel : WSBalanceClient.AccountAndNameLinkInfoService.IAccountAndNameLinkInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountAndNameLinkInfoServiceClient : System.ServiceModel.ClientBase<WSBalanceClient.AccountAndNameLinkInfoService.IAccountAndNameLinkInfoService>, WSBalanceClient.AccountAndNameLinkInfoService.IAccountAndNameLinkInfoService {
        
        public AccountAndNameLinkInfoServiceClient() {
        }
        
        public AccountAndNameLinkInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountAndNameLinkInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountAndNameLinkInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountAndNameLinkInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(WSBalanceClient.AccountAndNameLinkInfoService.AccountAndNameLinkInfo info) {
            return base.Channel.Add(info);
        }
        
        public bool Update(WSBalanceClient.AccountAndNameLinkInfoService.AccountAndNameLinkInfo info) {
            return base.Channel.Update(info);
        }
        
        public bool Delete(WSBalanceClient.AccountAndNameLinkInfoService.AccountAndNameLinkInfo info) {
            return base.Channel.Delete(info);
        }
        
        public WSBalanceClient.AccountAndNameLinkInfoService.AccountAndNameLinkInfo[] Select(WSBalanceClient.AccountAndNameLinkInfoService.AccountAndNameLinkInfo info) {
            return base.Channel.Select(info);
        }
        
        public int SelectCount(WSBalanceClient.AccountAndNameLinkInfoService.AccountAndNameLinkInfo info) {
            return base.Channel.SelectCount(info);
        }
    }
}
