//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalanceReport.ServiceFile {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomFileInfo", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    public partial class CustomFileInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileRealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImportTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OffSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SendByteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileRealName {
            get {
                return this.FileRealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileRealNameField, value) != true)) {
                    this.FileRealNameField = value;
                    this.RaisePropertyChanged("FileRealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImportType {
            get {
                return this.ImportTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportTypeField, value) != true)) {
                    this.ImportTypeField = value;
                    this.RaisePropertyChanged("ImportType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OffSet {
            get {
                return this.OffSetField;
            }
            set {
                if ((this.OffSetField.Equals(value) != true)) {
                    this.OffSetField = value;
                    this.RaisePropertyChanged("OffSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SendByte {
            get {
                return this.SendByteField;
            }
            set {
                if ((object.ReferenceEquals(this.SendByteField, value) != true)) {
                    this.SendByteField = value;
                    this.RaisePropertyChanged("SendByte");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseModel", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BalanceReport.ServiceFile.UploadFileInfo))]
    public partial class BaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderbyColomnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubOrderbyColomnNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndIndex {
            get {
                return this.EndIndexField;
            }
            set {
                if ((this.EndIndexField.Equals(value) != true)) {
                    this.EndIndexField = value;
                    this.RaisePropertyChanged("EndIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderbyColomnName {
            get {
                return this.OrderbyColomnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderbyColomnNameField, value) != true)) {
                    this.OrderbyColomnNameField = value;
                    this.RaisePropertyChanged("OrderbyColomnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowNumber {
            get {
                return this.RowNumberField;
            }
            set {
                if ((this.RowNumberField.Equals(value) != true)) {
                    this.RowNumberField = value;
                    this.RaisePropertyChanged("RowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartIndex {
            get {
                return this.StartIndexField;
            }
            set {
                if ((this.StartIndexField.Equals(value) != true)) {
                    this.StartIndexField = value;
                    this.RaisePropertyChanged("StartIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubOrderbyColomnName {
            get {
                return this.SubOrderbyColomnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubOrderbyColomnNameField, value) != true)) {
                    this.SubOrderbyColomnNameField = value;
                    this.RaisePropertyChanged("SubOrderbyColomnName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadFileInfo", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    public partial class UploadFileInfo : BalanceReport.ServiceFile.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FileDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileMD5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileRealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FileStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FileUploadTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOverrideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FileDateTime {
            get {
                return this.FileDateTimeField;
            }
            set {
                if ((this.FileDateTimeField.Equals(value) != true)) {
                    this.FileDateTimeField = value;
                    this.RaisePropertyChanged("FileDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileException {
            get {
                return this.FileExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FileExceptionField, value) != true)) {
                    this.FileExceptionField = value;
                    this.RaisePropertyChanged("FileException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileMD5 {
            get {
                return this.FileMD5Field;
            }
            set {
                if ((object.ReferenceEquals(this.FileMD5Field, value) != true)) {
                    this.FileMD5Field = value;
                    this.RaisePropertyChanged("FileMD5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath {
            get {
                return this.FilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.FilePathField, value) != true)) {
                    this.FilePathField = value;
                    this.RaisePropertyChanged("FilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileRealName {
            get {
                return this.FileRealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileRealNameField, value) != true)) {
                    this.FileRealNameField = value;
                    this.RaisePropertyChanged("FileRealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileState {
            get {
                return this.FileStateField;
            }
            set {
                if ((this.FileStateField.Equals(value) != true)) {
                    this.FileStateField = value;
                    this.RaisePropertyChanged("FileState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileType {
            get {
                return this.FileTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FileTypeField, value) != true)) {
                    this.FileTypeField = value;
                    this.RaisePropertyChanged("FileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FileUploadTime {
            get {
                return this.FileUploadTimeField;
            }
            set {
                if ((this.FileUploadTimeField.Equals(value) != true)) {
                    this.FileUploadTimeField = value;
                    this.RaisePropertyChanged("FileUploadTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOverride {
            get {
                return this.IsOverrideField;
            }
            set {
                if ((this.IsOverrideField.Equals(value) != true)) {
                    this.IsOverrideField = value;
                    this.RaisePropertyChanged("IsOverride");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceFile.IServiceFile")]
    public interface IServiceFile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFile/UpLoadFileInfo", ReplyAction="http://tempuri.org/IServiceFile/UpLoadFileInfoResponse")]
        BalanceReport.ServiceFile.CustomFileInfo UpLoadFileInfo(BalanceReport.ServiceFile.CustomFileInfo fileInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFile/GetFileInfo", ReplyAction="http://tempuri.org/IServiceFile/GetFileInfoResponse")]
        BalanceReport.ServiceFile.UploadFileInfo GetFileInfo(BalanceReport.ServiceFile.UploadFileInfo uploadfileinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFile/StoreUpLoadResult", ReplyAction="http://tempuri.org/IServiceFile/StoreUpLoadResultResponse")]
        bool StoreUpLoadResult(BalanceReport.ServiceFile.UploadFileInfo uploadfileinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFile/Select", ReplyAction="http://tempuri.org/IServiceFile/SelectResponse")]
        BalanceReport.ServiceFile.UploadFileInfo[] Select(BalanceReport.ServiceFile.UploadFileInfo uploadfileinfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceFileChannel : BalanceReport.ServiceFile.IServiceFile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceFileClient : System.ServiceModel.ClientBase<BalanceReport.ServiceFile.IServiceFile>, BalanceReport.ServiceFile.IServiceFile {
        
        public ServiceFileClient() {
        }
        
        public ServiceFileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceFileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BalanceReport.ServiceFile.CustomFileInfo UpLoadFileInfo(BalanceReport.ServiceFile.CustomFileInfo fileInfo) {
            return base.Channel.UpLoadFileInfo(fileInfo);
        }
        
        public BalanceReport.ServiceFile.UploadFileInfo GetFileInfo(BalanceReport.ServiceFile.UploadFileInfo uploadfileinfo) {
            return base.Channel.GetFileInfo(uploadfileinfo);
        }
        
        public bool StoreUpLoadResult(BalanceReport.ServiceFile.UploadFileInfo uploadfileinfo) {
            return base.Channel.StoreUpLoadResult(uploadfileinfo);
        }
        
        public BalanceReport.ServiceFile.UploadFileInfo[] Select(BalanceReport.ServiceFile.UploadFileInfo uploadfileinfo) {
            return base.Channel.Select(uploadfileinfo);
        }
    }
}
