//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalanceReport.SystemSetInfoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseModel", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BalanceReport.SystemSetInfoService.SystemSetInfo))]
    public partial class BaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderbyColomnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartIndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndIndex {
            get {
                return this.EndIndexField;
            }
            set {
                if ((this.EndIndexField.Equals(value) != true)) {
                    this.EndIndexField = value;
                    this.RaisePropertyChanged("EndIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderbyColomnName {
            get {
                return this.OrderbyColomnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderbyColomnNameField, value) != true)) {
                    this.OrderbyColomnNameField = value;
                    this.RaisePropertyChanged("OrderbyColomnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowNumber {
            get {
                return this.RowNumberField;
            }
            set {
                if ((this.RowNumberField.Equals(value) != true)) {
                    this.RowNumberField = value;
                    this.RaisePropertyChanged("RowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartIndex {
            get {
                return this.StartIndexField;
            }
            set {
                if ((this.StartIndexField.Equals(value) != true)) {
                    this.StartIndexField = value;
                    this.RaisePropertyChanged("StartIndex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemSetInfo", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    public partial class SystemSetInfo : BalanceReport.SystemSetInfoService.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SetContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SetNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SetContent {
            get {
                return this.SetContentField;
            }
            set {
                if ((object.ReferenceEquals(this.SetContentField, value) != true)) {
                    this.SetContentField = value;
                    this.RaisePropertyChanged("SetContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SetName {
            get {
                return this.SetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SetNameField, value) != true)) {
                    this.SetNameField = value;
                    this.RaisePropertyChanged("SetName");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SystemSetInfoService.ISystemSetInfoService")]
    public interface ISystemSetInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemSetInfoService/Add", ReplyAction="http://tempuri.org/ISystemSetInfoService/AddResponse")]
        bool Add(BalanceReport.SystemSetInfoService.SystemSetInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemSetInfoService/Update", ReplyAction="http://tempuri.org/ISystemSetInfoService/UpdateResponse")]
        bool Update(BalanceReport.SystemSetInfoService.SystemSetInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemSetInfoService/Delete", ReplyAction="http://tempuri.org/ISystemSetInfoService/DeleteResponse")]
        bool Delete(BalanceReport.SystemSetInfoService.SystemSetInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemSetInfoService/Select", ReplyAction="http://tempuri.org/ISystemSetInfoService/SelectResponse")]
        BalanceReport.SystemSetInfoService.SystemSetInfo[] Select(BalanceReport.SystemSetInfoService.SystemSetInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemSetInfoService/SelectCount", ReplyAction="http://tempuri.org/ISystemSetInfoService/SelectCountResponse")]
        int SelectCount(BalanceReport.SystemSetInfoService.SystemSetInfo info);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISystemSetInfoServiceChannel : BalanceReport.SystemSetInfoService.ISystemSetInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemSetInfoServiceClient : System.ServiceModel.ClientBase<BalanceReport.SystemSetInfoService.ISystemSetInfoService>, BalanceReport.SystemSetInfoService.ISystemSetInfoService {
        
        public SystemSetInfoServiceClient() {
        }
        
        public SystemSetInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemSetInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemSetInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemSetInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(BalanceReport.SystemSetInfoService.SystemSetInfo info) {
            return base.Channel.Add(info);
        }
        
        public bool Update(BalanceReport.SystemSetInfoService.SystemSetInfo info) {
            return base.Channel.Update(info);
        }
        
        public bool Delete(BalanceReport.SystemSetInfoService.SystemSetInfo info) {
            return base.Channel.Delete(info);
        }
        
        public BalanceReport.SystemSetInfoService.SystemSetInfo[] Select(BalanceReport.SystemSetInfoService.SystemSetInfo info) {
            return base.Channel.Select(info);
        }
        
        public int SelectCount(BalanceReport.SystemSetInfoService.SystemSetInfo info) {
            return base.Channel.SelectCount(info);
        }
    }
}
