//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSBalanceClient.PGWebistePerformanceInfoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseModel", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGWebistePerformanceInfoService.WebsiteInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGWebistePerformanceInfoService.PersonGoldBaseModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGWebistePerformanceInfoService.PGDebitCardInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGWebistePerformanceInfoService.PGInsuranceInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo))]
    public partial class BaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderbyColomnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubOrderbyColomnNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndIndex {
            get {
                return this.EndIndexField;
            }
            set {
                if ((this.EndIndexField.Equals(value) != true)) {
                    this.EndIndexField = value;
                    this.RaisePropertyChanged("EndIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderbyColomnName {
            get {
                return this.OrderbyColomnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderbyColomnNameField, value) != true)) {
                    this.OrderbyColomnNameField = value;
                    this.RaisePropertyChanged("OrderbyColomnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowNumber {
            get {
                return this.RowNumberField;
            }
            set {
                if ((this.RowNumberField.Equals(value) != true)) {
                    this.RowNumberField = value;
                    this.RaisePropertyChanged("RowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartIndex {
            get {
                return this.StartIndexField;
            }
            set {
                if ((this.StartIndexField.Equals(value) != true)) {
                    this.StartIndexField = value;
                    this.RaisePropertyChanged("StartIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubOrderbyColomnName {
            get {
                return this.SubOrderbyColomnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubOrderbyColomnNameField, value) != true)) {
                    this.SubOrderbyColomnNameField = value;
                    this.RaisePropertyChanged("SubOrderbyColomnName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebsiteInfo", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    public partial class WebsiteInfo : WSBalanceClient.PGWebistePerformanceInfoService.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagerTelphoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewWebsiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteTelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Institution {
            get {
                return this.InstitutionField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitutionField, value) != true)) {
                    this.InstitutionField = value;
                    this.RaisePropertyChanged("Institution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerTelphone {
            get {
                return this.ManagerTelphoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerTelphoneField, value) != true)) {
                    this.ManagerTelphoneField = value;
                    this.RaisePropertyChanged("ManagerTelphone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewWebsiteID {
            get {
                return this.NewWebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NewWebsiteIDField, value) != true)) {
                    this.NewWebsiteIDField = value;
                    this.RaisePropertyChanged("NewWebsiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteAddress {
            get {
                return this.WebsiteAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteAddressField, value) != true)) {
                    this.WebsiteAddressField = value;
                    this.RaisePropertyChanged("WebsiteAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteID {
            get {
                return this.WebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteIDField, value) != true)) {
                    this.WebsiteIDField = value;
                    this.RaisePropertyChanged("WebsiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteManager {
            get {
                return this.WebsiteManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteManagerField, value) != true)) {
                    this.WebsiteManagerField = value;
                    this.RaisePropertyChanged("WebsiteManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteName {
            get {
                return this.WebsiteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteNameField, value) != true)) {
                    this.WebsiteNameField = value;
                    this.RaisePropertyChanged("WebsiteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteTel {
            get {
                return this.WebsiteTelField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteTelField, value) != true)) {
                    this.WebsiteTelField = value;
                    this.RaisePropertyChanged("WebsiteTel");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonGoldBaseModel", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGWebistePerformanceInfoService.PGDebitCardInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGWebistePerformanceInfoService.PGInsuranceInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo))]
    public partial class PersonGoldBaseModel : WSBalanceClient.PGWebistePerformanceInfoService.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewWebsiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataTime {
            get {
                return this.DataTimeField;
            }
            set {
                if ((this.DataTimeField.Equals(value) != true)) {
                    this.DataTimeField = value;
                    this.RaisePropertyChanged("DataTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewWebsiteID {
            get {
                return this.NewWebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NewWebsiteIDField, value) != true)) {
                    this.NewWebsiteIDField = value;
                    this.RaisePropertyChanged("NewWebsiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteID {
            get {
                return this.WebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteIDField, value) != true)) {
                    this.WebsiteIDField = value;
                    this.RaisePropertyChanged("WebsiteID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PGDebitCardInfo", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    public partial class PGDebitCardInfo : WSBalanceClient.PGWebistePerformanceInfoService.PersonGoldBaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrentDayBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrentMonthAverageBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrentYearAverageBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DifferenceValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSBalanceClient.PGWebistePerformanceInfoService.WebsiteInfo WebsiteInfoObjField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CurrentDayBalance {
            get {
                return this.CurrentDayBalanceField;
            }
            set {
                if ((this.CurrentDayBalanceField.Equals(value) != true)) {
                    this.CurrentDayBalanceField = value;
                    this.RaisePropertyChanged("CurrentDayBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CurrentMonthAverageBalance {
            get {
                return this.CurrentMonthAverageBalanceField;
            }
            set {
                if ((this.CurrentMonthAverageBalanceField.Equals(value) != true)) {
                    this.CurrentMonthAverageBalanceField = value;
                    this.RaisePropertyChanged("CurrentMonthAverageBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CurrentYearAverageBalance {
            get {
                return this.CurrentYearAverageBalanceField;
            }
            set {
                if ((this.CurrentYearAverageBalanceField.Equals(value) != true)) {
                    this.CurrentYearAverageBalanceField = value;
                    this.RaisePropertyChanged("CurrentYearAverageBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DifferenceValue {
            get {
                return this.DifferenceValueField;
            }
            set {
                if ((this.DifferenceValueField.Equals(value) != true)) {
                    this.DifferenceValueField = value;
                    this.RaisePropertyChanged("DifferenceValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSBalanceClient.PGWebistePerformanceInfoService.WebsiteInfo WebsiteInfoObj {
            get {
                return this.WebsiteInfoObjField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteInfoObjField, value) != true)) {
                    this.WebsiteInfoObjField = value;
                    this.RaisePropertyChanged("WebsiteInfoObj");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PGInsuranceInfo", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    public partial class PGInsuranceInfo : WSBalanceClient.PGWebistePerformanceInfoService.PersonGoldBaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrentDayBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrentYearAverageBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DifferenceValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSBalanceClient.PGWebistePerformanceInfoService.WebsiteInfo WebsiteInfoObjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WholeBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CurrentDayBalance {
            get {
                return this.CurrentDayBalanceField;
            }
            set {
                if ((this.CurrentDayBalanceField.Equals(value) != true)) {
                    this.CurrentDayBalanceField = value;
                    this.RaisePropertyChanged("CurrentDayBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CurrentYearAverageBalance {
            get {
                return this.CurrentYearAverageBalanceField;
            }
            set {
                if ((this.CurrentYearAverageBalanceField.Equals(value) != true)) {
                    this.CurrentYearAverageBalanceField = value;
                    this.RaisePropertyChanged("CurrentYearAverageBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DifferenceValue {
            get {
                return this.DifferenceValueField;
            }
            set {
                if ((this.DifferenceValueField.Equals(value) != true)) {
                    this.DifferenceValueField = value;
                    this.RaisePropertyChanged("DifferenceValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSBalanceClient.PGWebistePerformanceInfoService.WebsiteInfo WebsiteInfoObj {
            get {
                return this.WebsiteInfoObjField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteInfoObjField, value) != true)) {
                    this.WebsiteInfoObjField = value;
                    this.RaisePropertyChanged("WebsiteInfoObj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> WholeBalance {
            get {
                return this.WholeBalanceField;
            }
            set {
                if ((this.WholeBalanceField.Equals(value) != true)) {
                    this.WholeBalanceField = value;
                    this.RaisePropertyChanged("WholeBalance");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PGWebistePerformanceInfo", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    public partial class PGWebistePerformanceInfo : WSBalanceClient.PGWebistePerformanceInfoService.PersonGoldBaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSBalanceClient.PGWebistePerformanceInfoService.PGDebitCardInfo PGDebitCardInfoObjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSBalanceClient.PGWebistePerformanceInfoService.PGInsuranceInfo PGInsuranceInfoObjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSBalanceClient.PGWebistePerformanceInfoService.WebsiteInfo WebsiteInfoObjField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSBalanceClient.PGWebistePerformanceInfoService.PGDebitCardInfo PGDebitCardInfoObj {
            get {
                return this.PGDebitCardInfoObjField;
            }
            set {
                if ((object.ReferenceEquals(this.PGDebitCardInfoObjField, value) != true)) {
                    this.PGDebitCardInfoObjField = value;
                    this.RaisePropertyChanged("PGDebitCardInfoObj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSBalanceClient.PGWebistePerformanceInfoService.PGInsuranceInfo PGInsuranceInfoObj {
            get {
                return this.PGInsuranceInfoObjField;
            }
            set {
                if ((object.ReferenceEquals(this.PGInsuranceInfoObjField, value) != true)) {
                    this.PGInsuranceInfoObjField = value;
                    this.RaisePropertyChanged("PGInsuranceInfoObj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSBalanceClient.PGWebistePerformanceInfoService.WebsiteInfo WebsiteInfoObj {
            get {
                return this.WebsiteInfoObjField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteInfoObjField, value) != true)) {
                    this.WebsiteInfoObjField = value;
                    this.RaisePropertyChanged("WebsiteInfoObj");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PGWebistePerformanceInfoService.IPGWebistePerformanceInfoService")]
    public interface IPGWebistePerformanceInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGWebistePerformanceInfoService/Add", ReplyAction="http://tempuri.org/IPGWebistePerformanceInfoService/AddResponse")]
        bool Add(WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGWebistePerformanceInfoService/Update", ReplyAction="http://tempuri.org/IPGWebistePerformanceInfoService/UpdateResponse")]
        bool Update(WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGWebistePerformanceInfoService/Delete", ReplyAction="http://tempuri.org/IPGWebistePerformanceInfoService/DeleteResponse")]
        bool Delete(WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGWebistePerformanceInfoService/Select", ReplyAction="http://tempuri.org/IPGWebistePerformanceInfoService/SelectResponse")]
        WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo[] Select(WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGWebistePerformanceInfoService/SelectCount", ReplyAction="http://tempuri.org/IPGWebistePerformanceInfoService/SelectCountResponse")]
        int SelectCount(WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGWebistePerformanceInfoService/CallTimeSpanProc", ReplyAction="http://tempuri.org/IPGWebistePerformanceInfoService/CallTimeSpanProcResponse")]
        WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo[] CallTimeSpanProc(WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo t);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPGWebistePerformanceInfoServiceChannel : WSBalanceClient.PGWebistePerformanceInfoService.IPGWebistePerformanceInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PGWebistePerformanceInfoServiceClient : System.ServiceModel.ClientBase<WSBalanceClient.PGWebistePerformanceInfoService.IPGWebistePerformanceInfoService>, WSBalanceClient.PGWebistePerformanceInfoService.IPGWebistePerformanceInfoService {
        
        public PGWebistePerformanceInfoServiceClient() {
        }
        
        public PGWebistePerformanceInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PGWebistePerformanceInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PGWebistePerformanceInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PGWebistePerformanceInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo info) {
            return base.Channel.Add(info);
        }
        
        public bool Update(WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo info) {
            return base.Channel.Update(info);
        }
        
        public bool Delete(WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo info) {
            return base.Channel.Delete(info);
        }
        
        public WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo[] Select(WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo info) {
            return base.Channel.Select(info);
        }
        
        public int SelectCount(WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo info) {
            return base.Channel.SelectCount(info);
        }
        
        public WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo[] CallTimeSpanProc(WSBalanceClient.PGWebistePerformanceInfoService.PGWebistePerformanceInfo t) {
            return base.Channel.CallTimeSpanProc(t);
        }
    }
}
