//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSBalanceClient.PGPersonInfoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseModel", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGPersonInfoService.WebsiteInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGPersonInfoService.PersonGoldBaseModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGPersonInfoService.PGPersonInfo))]
    public partial class BaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderbyColomnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubOrderbyColomnNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndIndex {
            get {
                return this.EndIndexField;
            }
            set {
                if ((this.EndIndexField.Equals(value) != true)) {
                    this.EndIndexField = value;
                    this.RaisePropertyChanged("EndIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderbyColomnName {
            get {
                return this.OrderbyColomnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderbyColomnNameField, value) != true)) {
                    this.OrderbyColomnNameField = value;
                    this.RaisePropertyChanged("OrderbyColomnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowNumber {
            get {
                return this.RowNumberField;
            }
            set {
                if ((this.RowNumberField.Equals(value) != true)) {
                    this.RowNumberField = value;
                    this.RaisePropertyChanged("RowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartIndex {
            get {
                return this.StartIndexField;
            }
            set {
                if ((this.StartIndexField.Equals(value) != true)) {
                    this.StartIndexField = value;
                    this.RaisePropertyChanged("StartIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubOrderbyColomnName {
            get {
                return this.SubOrderbyColomnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubOrderbyColomnNameField, value) != true)) {
                    this.SubOrderbyColomnNameField = value;
                    this.RaisePropertyChanged("SubOrderbyColomnName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebsiteInfo", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    public partial class WebsiteInfo : WSBalanceClient.PGPersonInfoService.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagerTelphoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewWebsiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteTelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Institution {
            get {
                return this.InstitutionField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitutionField, value) != true)) {
                    this.InstitutionField = value;
                    this.RaisePropertyChanged("Institution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerTelphone {
            get {
                return this.ManagerTelphoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerTelphoneField, value) != true)) {
                    this.ManagerTelphoneField = value;
                    this.RaisePropertyChanged("ManagerTelphone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewWebsiteID {
            get {
                return this.NewWebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NewWebsiteIDField, value) != true)) {
                    this.NewWebsiteIDField = value;
                    this.RaisePropertyChanged("NewWebsiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteAddress {
            get {
                return this.WebsiteAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteAddressField, value) != true)) {
                    this.WebsiteAddressField = value;
                    this.RaisePropertyChanged("WebsiteAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteID {
            get {
                return this.WebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteIDField, value) != true)) {
                    this.WebsiteIDField = value;
                    this.RaisePropertyChanged("WebsiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteManager {
            get {
                return this.WebsiteManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteManagerField, value) != true)) {
                    this.WebsiteManagerField = value;
                    this.RaisePropertyChanged("WebsiteManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteName {
            get {
                return this.WebsiteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteNameField, value) != true)) {
                    this.WebsiteNameField = value;
                    this.RaisePropertyChanged("WebsiteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteTel {
            get {
                return this.WebsiteTelField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteTelField, value) != true)) {
                    this.WebsiteTelField = value;
                    this.RaisePropertyChanged("WebsiteTel");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonGoldBaseModel", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSBalanceClient.PGPersonInfoService.PGPersonInfo))]
    public partial class PersonGoldBaseModel : WSBalanceClient.PGPersonInfoService.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewWebsiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataTime {
            get {
                return this.DataTimeField;
            }
            set {
                if ((this.DataTimeField.Equals(value) != true)) {
                    this.DataTimeField = value;
                    this.RaisePropertyChanged("DataTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewWebsiteID {
            get {
                return this.NewWebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.NewWebsiteIDField, value) != true)) {
                    this.NewWebsiteIDField = value;
                    this.RaisePropertyChanged("NewWebsiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebsiteID {
            get {
                return this.WebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteIDField, value) != true)) {
                    this.WebsiteIDField = value;
                    this.RaisePropertyChanged("WebsiteID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PGPersonInfo", Namespace="http://schemas.datacontract.org/2004/07/BalanceModel")]
    [System.SerializableAttribute()]
    public partial class PGPersonInfo : WSBalanceClient.PGPersonInfoService.PersonGoldBaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffPositionOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSBalanceClient.PGPersonInfoService.WebsiteInfo WebsiteInfoObjField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardID {
            get {
                return this.CardIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CardIDField, value) != true)) {
                    this.CardIDField = value;
                    this.RaisePropertyChanged("CardID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffCode {
            get {
                return this.StaffCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffCodeField, value) != true)) {
                    this.StaffCodeField = value;
                    this.RaisePropertyChanged("StaffCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffName {
            get {
                return this.StaffNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffNameField, value) != true)) {
                    this.StaffNameField = value;
                    this.RaisePropertyChanged("StaffName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffPosition {
            get {
                return this.StaffPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffPositionField, value) != true)) {
                    this.StaffPositionField = value;
                    this.RaisePropertyChanged("StaffPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffPositionOrder {
            get {
                return this.StaffPositionOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffPositionOrderField, value) != true)) {
                    this.StaffPositionOrderField = value;
                    this.RaisePropertyChanged("StaffPositionOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffType {
            get {
                return this.StaffTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffTypeField, value) != true)) {
                    this.StaffTypeField = value;
                    this.RaisePropertyChanged("StaffType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSBalanceClient.PGPersonInfoService.WebsiteInfo WebsiteInfoObj {
            get {
                return this.WebsiteInfoObjField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteInfoObjField, value) != true)) {
                    this.WebsiteInfoObjField = value;
                    this.RaisePropertyChanged("WebsiteInfoObj");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PGPersonInfoService.IPGPersonInfoService")]
    public interface IPGPersonInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGPersonInfoService/Add", ReplyAction="http://tempuri.org/IPGPersonInfoService/AddResponse")]
        bool Add(WSBalanceClient.PGPersonInfoService.PGPersonInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGPersonInfoService/Update", ReplyAction="http://tempuri.org/IPGPersonInfoService/UpdateResponse")]
        bool Update(WSBalanceClient.PGPersonInfoService.PGPersonInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGPersonInfoService/Delete", ReplyAction="http://tempuri.org/IPGPersonInfoService/DeleteResponse")]
        bool Delete(WSBalanceClient.PGPersonInfoService.PGPersonInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGPersonInfoService/Select", ReplyAction="http://tempuri.org/IPGPersonInfoService/SelectResponse")]
        WSBalanceClient.PGPersonInfoService.PGPersonInfo[] Select(WSBalanceClient.PGPersonInfoService.PGPersonInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGPersonInfoService/SelectCount", ReplyAction="http://tempuri.org/IPGPersonInfoService/SelectCountResponse")]
        int SelectCount(WSBalanceClient.PGPersonInfoService.PGPersonInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPGPersonInfoService/CallTimeSpanProc", ReplyAction="http://tempuri.org/IPGPersonInfoService/CallTimeSpanProcResponse")]
        WSBalanceClient.PGPersonInfoService.PGPersonInfo[] CallTimeSpanProc(WSBalanceClient.PGPersonInfoService.PGPersonInfo t);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPGPersonInfoServiceChannel : WSBalanceClient.PGPersonInfoService.IPGPersonInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PGPersonInfoServiceClient : System.ServiceModel.ClientBase<WSBalanceClient.PGPersonInfoService.IPGPersonInfoService>, WSBalanceClient.PGPersonInfoService.IPGPersonInfoService {
        
        public PGPersonInfoServiceClient() {
        }
        
        public PGPersonInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PGPersonInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PGPersonInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PGPersonInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(WSBalanceClient.PGPersonInfoService.PGPersonInfo info) {
            return base.Channel.Add(info);
        }
        
        public bool Update(WSBalanceClient.PGPersonInfoService.PGPersonInfo info) {
            return base.Channel.Update(info);
        }
        
        public bool Delete(WSBalanceClient.PGPersonInfoService.PGPersonInfo info) {
            return base.Channel.Delete(info);
        }
        
        public WSBalanceClient.PGPersonInfoService.PGPersonInfo[] Select(WSBalanceClient.PGPersonInfoService.PGPersonInfo info) {
            return base.Channel.Select(info);
        }
        
        public int SelectCount(WSBalanceClient.PGPersonInfoService.PGPersonInfo info) {
            return base.Channel.SelectCount(info);
        }
        
        public WSBalanceClient.PGPersonInfoService.PGPersonInfo[] CallTimeSpanProc(WSBalanceClient.PGPersonInfoService.PGPersonInfo t) {
            return base.Channel.CallTimeSpanProc(t);
        }
    }
}
